spring.application.name=cc-food-recall
spring.datasource.url=jdbc:h2:file:./data/cc-food-recall
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
